name: bindings/build-ffi

on: workflow_dispatch

jobs:  
  build-ffi:
    name: 'Build Regorus FFI: (${{ matrix.runtime.target }})'
    runs-on: ${{ matrix.runtime.os }}
    strategy:
      fail-fast: false
      matrix:
        runtime:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            libpath: |
              **/release/regorus_ffi.dll
              **/release/regorus_ffi.pdb
              RegorusFFI.g.cs
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            libpath: |
              **/release/libregorus_ffi.so
              RegorusFFI.g.cs
          - os: macos-latest
            target: aarch64-apple-darwin
            libpath: |
              **/release/libregorus_ffi.dylib
              RegorusFFI.g.cs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Regorus binding
        run: cargo build -r --target ${{ matrix.runtime.target }} --locked
        working-directory: ./bindings/ffi
        
      - name: Upload regorus ffi shared library
        uses: actions/upload-artifact@v4
        with:
          name: regorus-ffi-artifacts-${{ matrix.runtime.target }}
          path: ${{ matrix.runtime.libpath }}
          if-no-files-found: error
          retention-days: 1
